sudo: required
services:
  - docker

before_install:
  - docker build -t lispavel/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lispavel/react-test npm test

after_success:
  - docker build -t lispavel/multi-client ./client
  - docker build -t lispavel/multi-nginx ./nginx
  - docker build -t lispavel/multi-server ./server
  - docker build -t lispavel/multi-worker ./worker